# Generated by Django 6.1.1 on 2026-09-13 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notes.tag",
            ),
        ),
    ]
