# Generated by Django 6.1.1 on 2026-09-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_note_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="tag",
        ),
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(blank=True, to="notes.tag"),
        ),
    ]
